# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    instagram.media_retriever:
        class: AppBundle\Instagram\MediaRetriever
        calls:
            - [ setContainer, [ @service_container ]]
            - [ setMediaManager, [ @instagram.media_manager ]]
    instagram.user_retriever:
        class: AppBundle\Instagram\UserRetriever
        calls:
            - [ setContainer, [ @service_container ]]
            - [ setStorageKey, [ instagram.users ]]
    instagram.media_manager:
        class: AppBundle\Instagram\MediaManager
        calls:
            - [ setContainer, [ @service_container ]]
            - [ setSavePath, [ %kernel.root_dir% ]]
            - [ setImageTmpFolder, [ tmp/image_cache ]]
